[package]
name = "typestate-builder-rust"
version = "0.1.0"
edition = "2021"
authors = ["Marius Wörfel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
