name: "CI_Java"

on:
  push:
    branches: "*"

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typestate-builder-java
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Validate
        run: mvn validate

      - name: Compile
        run: mvn compile

      - name: Test
        run: mvn test

  package:
    name: "Package"
    needs: "test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typestate-builder-java
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Package
        run: mvn package
